repos:
- hooks:
  - id: terraform_fmt
  - args:
    - --args=--config=.terraform-docs.yml
    id: terraform_docs
  - args:
    - --args=--only=terraform_deprecated_interpolation
    - --args=--only=terraform_deprecated_index
    - --args=--only=terraform_module_pinned_source
    - --args=--only=terraform_naming_convention
    - --args=--only=terraform_workspace_remote
    id: terraform_tflint
  repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
- hooks:
  - args:
    - --compact
    - --quiet
    - --skip-check
    - CKV_AZURE_1,CKV_AZURE_35,CKV_AZURE_44,CKV_AZURE_49,CKV_AZURE_59,CKV_AZURE_93,CKV_AZURE_97,CKV_AZURE_118,CKV_AZURE_119,CKV_AZURE_120,CKV_AZURE_179,CKV_AZURE_190,CKV_AZURE_206,CKV_AZURE_217,CKV_AZURE_218,CKV2_AZURE_1,CKV2_AZURE_10,CKV2_AZURE_12,CKV2_AZURE_18,CKV2_AZURE_33,CKV2_AZURE_39,CKV2_AZURE_40,CKV2_AZURE_41
    id: checkov
    verbose: true
  repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.2.50
