formatter: "markdown document" # this is required
version: ""
header-from: ".header.md"

output:
  file: .README.md
  mode: replace
  template: |-
    {{ .Content }}

sort:
  enabled: false

settings:
  indent: 3
  lockfile: false
  escape: false

content: |-
  {{ .Header }}

  ## Reference

  {{ if ne (len .Module.Requirements) 0 -}}
  ### Requirements
  {{ range .Module.Requirements }}
  - `{{ .Name }}`{{ if .Version }}, version: {{ .Version }}{{ end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Providers) 0 -}}
  ### Providers
  {{ range .Module.Providers }}
  - `{{ .Name }}`{{ if .Version }}, version: {{ .Version }}{{ end }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.ModuleCalls) 0 -}}
  ### Modules
  Name | Version | Source | Description
  --- | --- | --- | ---
  {{- range .Module.ModuleCalls }}
  `{{ .Name }}` | {{ if .Version }}{{ .Version }}{{ else }}-{{ end }} | {{ .Source }} | {{ .Description }}
  {{- end }}
  {{- end }}

  {{ if ne (len .Module.Resources) 0 -}}
  ### Resources
  {{ range .Module.Resources }}
  - `{{ .Type }}` ({{ .Mode }})
  {{- end }}
  {{- end }}

  ### Required Inputs

  Name | Type | Description
  --- | --- | ---
  {{- range .Module.Inputs }}
  {{- if .Required }}
  [`{{ .Name }}`](#{{ .Name }}) | `{{ (split "(" .Type.Raw)._0 }}` | {{ (split "." .Description.Raw)._0 }}.
  {{- end }}
  {{- end }}

  {{ $optional := false -}}
  {{ range .Module.Inputs }}{{ if not .Required }}{{ $optional = true -}}{{ end -}}{{ end -}}

  {{ if $optional -}}
  ### Optional Inputs

  Name | Type | Description
  --- | --- | ---
  {{- range .Module.Inputs }}
  {{- if not .Required }}
  [`{{ .Name }}`](#{{ .Name }}) | `{{ (split "(" .Type.Raw)._0 }}` | {{ (split "." .Description.Raw)._0 }}.
  {{- end -}}
  {{ end -}}
  {{ end }}

  {{ if ne (len .Module.Outputs) 0 -}}
  ### Outputs

  Name |  Description
  --- | ---
  {{- range .Module.Outputs }}
  `{{ .Name }}` | {{ .Description.Raw }}
  {{- end }}
  {{- end }}

  ### Required Inputs details

  {{ range .Module.Inputs -}}
  {{ if .Required -}}
  #### {{ .Name }}

  {{ .Description }}

  Type: {{ if lt (len (split "\n" .Type.Raw)) 2 }}{{ .Type }}{{ else }}

  ```hcl
  {{ .Type }}
  ```
  {{ end }}

  <sup>[back to list](#modules-required-inputs)</sup>
  
  {{ end -}}
  {{- end -}}

  {{ if $optional -}}
  ### Optional Inputs details

  {{ range .Module.Inputs -}}
  {{ if not .Required -}}
  #### {{ .Name }}

  {{ .Description }}

  Type: {{ if lt (len (split "\n" .Type.Raw)) 2 }}{{ .Type }}{{ else }}

  ```hcl
  {{ .Type }}
  ```
  {{ end }}

  Default value: `{{ .Default }}`

  <sup>[back to list](#modules-optional-inputs)</sup>
  
  {{ end }}
  {{- end -}}
  {{ end -}}