name: Orchestrator Hub Sync System Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 4" # this means every Thursday @3am UTC

jobs:
  hub_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.HUB_SYNC_APP_ID }}
          private_key: ${{ secrets.HUB_SYNC_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.HUB_SYNC_APP_INSTALLATION_ID }}

      - name: Trigger Hub Sync Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run.yml
          repo: PaloAltoNetworks/automation-metadata-collector
          ref: main
          token: ${{ steps.generate-token.outputs.token }}
          inputs: '{"cloud-id": "azure"}'
